django_60075/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('productos/', include('productos.urls')),
    path('usuarios/', include('usuarios.urls'))
    
]

inicio/urls.py
from django.urls import path
from inicio.views import (
    mi_vista, 
    inicio, 
    vista_datos1, 
    primer_template, 
    segundo_template, 
    crear_auto_correcto,
    buscar_auto, crear_auto,
    ver_auto, eliminar_auto, 
    editar_auto
)
app_name = "inicio"

urlpatterns = [
    path("mi-vista/", mi_vista, name="mi_vista"),
    path('', inicio, name="inicio"),
    path('vista-datos1/<nombre>/', vista_datos1, name="vista_datos1"),
    path('primer-template/', primer_template, name="primer_template"),
    path('segundo-template/', segundo_template, name="segundo_template"),
    path('crear-auto-correcto/<str:marca>/<str:modelo>/<int:anio>/', crear_auto_correcto, name="crear_auto_correcto"),
    path('buscar-auto/', buscar_auto, name="buscar_auto"),
    path('crear-auto/', crear_auto, name="crear_auto"),
    path('ver-auto/<int:id>', ver_auto, name="ver_auto"),
    path('eliminar-auto/<int:id>', eliminar_auto, name="eliminar_auto"),
    path('editar-auto/<int:id>', editar_auto, name="editar_auto")
]

inicio/models.py
from django.db import models


# Create your models here.
class Auto(models.Model):
    marca = models.CharField(max_length=20)
    modelo = models.CharField(max_length=20)
    anio =  models.IntegerField()
    
    def __str__(self):
        return f'{self.id} {self.modelo} {self.anio}'

inicio/forms.py
from django import forms

class AutoFormularioBase(forms.Form):
    marca = forms.CharField(max_length=20)
    modelo = forms.CharField(max_length=20)
    anio = forms.IntegerField()
    
class CrearAutoFormulario(AutoFormularioBase): ...
   
    
class EditarAutoFormulario(AutoFormularioBase): ...
    
    
    
class BuscarAutoFormulario(forms.Form):
    marca = forms.CharField(max_length=20, required=False)
    modelo = forms.CharField(max_length=20, required=False)
    

inicio/views.py
from django.http import HttpResponse
from django.template import Template, Context, loader
from datetime import datetime
from django.shortcuts import render, redirect
from inicio.models import Auto
from inicio.forms import CrearAutoFormulario, BuscarAutoFormulario, EditarAutoFormulario
from django.contrib.auth.decorators import login_required

def mi_vista(request):
    return HttpResponse("Hola soy la vista")

def inicio(request):
    return render(request, 'inicio/index.html')

def vista_datos1(request, nombre):
    nombre_mayuscula = nombre.upper()
    return HttpResponse(f"Hola!! {nombre_mayuscula}")

def primer_template(request):
    # archivo_template = open(r'templates\primer_template.html')
    
    # template = Template(archivo_template.read())
    # archivo_template.close()
    # contexto = Context()
    
    #con with
    with open(r'templates\primer_template.html') as archivo_template:
        template = Template(archivo_template.read())
    
    contexto = Context()
    render_template = template.render(contexto)
    return HttpResponse(render_template)

def segundo_template(request):
    fecha_actual = datetime.now()
    datos = {'fecha_actual': fecha_actual,
             'numeros': list(range(1, 11))
    }
    
    #v1
    # with open(r'templates\segundo_template.html') as archivo_template:
    #     template = Template(archivo_template.read())
    # contexto = Context(datos)
    # render_template = template.render(contexto)
    
    #v2
    # template = loader.get_template('segundo_template.html')
    # render_template = template.render(datos)
    # return HttpResponse(render_template)

    #v3
    return render(request, 'inicio/segundo_template.html', datos)


def crear_auto_correcto(request,marca, modelo, anio):
    
    auto = Auto(marca=marca ,modelo=modelo,anio=anio) 
    auto.save()
    return render(request, 'inicio/creacion_auto_correcta.html', {'auto': auto})


def buscar_auto(request):
    
    formulario = BuscarAutoFormulario(request.GET)
    if formulario.is_valid():
        marca = formulario.cleaned_data.get('marca')
        modelo = formulario.cleaned_data.get('modelo')
        autos = Auto.objects.filter(marca__icontains = marca, modelo__icontains = modelo)
    else:    
        autos = Auto.objects.all()
        
    return render(request, 'inicio/buscar_auto.html', {'autos': autos, 'form': formulario})


def crear_auto(request):
    
    # print("Request", request)
    # print("GET", request.GET)
    # print("POST", request.POST)
    
    formulario = CrearAutoFormulario()
    
    if request.method == 'POST':
        # auto = Auto(marca=request.POST.get('marca'), modelo=request.POST.get('modelo'), anio=request.POST.get('anio')) 
        # auto.save()
        formulario = CrearAutoFormulario(request.POST)
        if formulario.is_valid():
            data = formulario.cleaned_data
            auto = Auto(marca=data.get('marca'), modelo=data.get('modelo'), anio=data.get('anio')) 
            auto.save()
            return redirect("inicio:buscar_auto")
    
    return render(request, 'inicio/crear_auto.html', {'form': formulario})


def ver_auto(request, id):
    auto = Auto.objects.get(id=id)
    return render(request, 'inicio/ver_auto.html', {'auto': auto})


@login_required
def eliminar_auto(request, id):
    auto = Auto.objects.get(id=id)
    auto.delete()
    return redirect('inicio:buscar_auto')

@login_required
def editar_auto(request, id):
    auto = Auto.objects.get(id=id)
    
    formulario = EditarAutoFormulario(initial={'modelo': auto.modelo, 'marca': auto.marca, 'anio':auto.anio})
    
    if request.method == "POST":
        formulario = EditarAutoFormulario(request.POST)
        if formulario.is_valid():
            auto.modelo = formulario.cleaned_data.get('modelo')
            auto.marca = formulario.cleaned_data.get('marca')
            auto.anio = formulario.cleaned_data.get('anio')
            
            auto.save() 
             
            return redirect('inicio:buscar_auto')
    return render(request, 'inicio/editar_auto.html', {'auto': auto,'form': formulario})
            
    

inicio/templates/inicio/buscar_auto.html
{% extends "inicio/index.html" %}
{% load static %}

{% block title_head %}
Buscar Auto
{% endblock title_head %}

{% block h1_header %}
Buscar Auto
{% endblock h1_header %}

{% block main %}
<form action={% url "inicio:buscar_auto" %}>
    {{form}}
    <input type="submit">
</form>

{% if autos %}
<ul>
    {% for auto in autos %}
    <li>
        {{auto}} | <a href={% url "inicio:ver_auto" auto.id %}>Ver más</a>
        | <a href={% url "inicio:editar_auto" auto.id %}>Editar</a>
        | <a href={% url "inicio:eliminar_auto" auto.id %}>Eliminar</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No hay autos registrados.</p>
{% endif %}

{% endblock main %}

inicio/templates/inicio/creacion_auto_correcta.html
{% extends "base.html" %}

{% block title_head %}
Creación de Auto
{% endblock title_head %}

{% block h1_header %}
<h1>Se creó el auto {{auto.id}} {{auto.marca}} correctamente</h1>
{% endblock h1_header %}

inicio/templates/inicio/crear_auto.html
{% extends "inicio/index.html" %}
{% load static %}

{% block title_head %}
Crear Auto
{% endblock title_head %}

{% block h1_header %}
Crear Auto
{% endblock h1_header %}

{% block main %}
<form action={% url "inicio:crear_auto" %} method="POST">
    {% csrf_token %}
    {% comment %} <p>
        Marca:
        <input type="text" name="marca">
    </p>
    <p>
        Modelo:
        <input type=" text" name="modelo">
    </p>
    <p>
        Anio:
        <input type=" number" name="anio">
    </p> {% endcomment %}
    
    {{form}}

    <input type="submit" value="Enviar">
    {% comment %} <button>Enviar</button> {% endcomment %}

</form>
{% endblock main %}

inicio/templates/inicio/editar_auto.html
{% extends "base.html" %}
{% load static %}

{% block title_head %}
Editar Auto
{% endblock title_head %}

{% block h1_header %}
Editar {{auto}}
{% endblock h1_header %}

{% block main %}
<form action={% url "inicio:editar_auto" auto.id %} method="POST">
    {% csrf_token %}

    {{form}}

    <input type="submit" value="Enviar">
</form>

{% endblock main %}

inicio/templates/inicio/index.html
{% extends "base.html" %}

{% block title_head %}
Inicio
{% endblock title_head %}

{% block h1_header %}
Soy la pantalla de inicio
{% endblock h1_header %}

inicio/templates/inicio/segundo_template.html
{% extends "inicio\index.html" %}
{% load static %}
{% block title_head %}
SegundoTemplate
{% endblock title_head %}

{% block h1_header %}
Segundo Template
{% endblock h1_header %}

{% block main %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        Daniel pudo con el codigo  2 !!!!!
    </h1>
    <h2>
       {{fecha_actual}} 
    </h2>
    <ul>esto es una li de ul</ul>
    <ol>esto es una li de ol</ol>
    <p>listado</p>
    <ul>
        {%for num in numeros%}
        {%if num > 5 %}
        <li>{{num}}</li>
        {%elif num == 5%}
        <li>Soy el mejor numero ... el 5</li>
        {%else%}
        <li>Soy menor a 5 soy el numero {{num}}</li>
        {%endif%}
        {%endfor%}
    </ul>
    <img src="assets/img/01.jpg" alt="">
</body>
</html>
{% endblock main %}

inicio/templates/inicio/ver_auto.html
{% extends "base.html" %}
{% load static %}

{% block title_head %}
Ver Auto
{% endblock title_head %}

{% block h1_header %}
{{auto}}
{% endblock h1_header %}

{% block main %}
<ul>
    <li>Marca: {{auto.marca}}</li>
    <li>Modelo: {{auto.modelo}}</li>
    <li>Anio: {{auto.anio}}</li>
</ul>

{% endblock main %}