django_60075/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('productos/', include('productos.urls')),
    path('usuarios/', include('usuarios.urls'))
    
]

inicio/urls.py
from django.urls import path
from inicio.views import (
    mi_vista, 
    inicio, 
    vista_datos1, 
    primer_template, 
    segundo_template, 
    crear_auto_correcto,
    buscar_auto, crear_auto,
    ver_auto, eliminar_auto, 
    editar_auto
)
app_name = "inicio"

urlpatterns = [
    path("mi-vista/", mi_vista, name="mi_vista"),
    path('', inicio, name="inicio"),
    path('vista-datos1/<nombre>/', vista_datos1, name="vista_datos1"),
    path('primer-template/', primer_template, name="primer_template"),
    path('segundo-template/', segundo_template, name="segundo_template"),
    path('crear-auto-correcto/<str:marca>/<str:modelo>/<int:anio>/', crear_auto_correcto, name="crear_auto_correcto"),
    path('buscar-auto/', buscar_auto, name="buscar_auto"),
    path('crear-auto/', crear_auto, name="crear_auto"),
    path('ver-auto/<int:id>', ver_auto, name="ver_auto"),
    path('eliminar-auto/<int:id>', eliminar_auto, name="eliminar_auto"),
    path('editar-auto/<int:id>', editar_auto, name="editar_auto")
]

productos/urls.py
from django.urls import path 
from productos import views

app_name = 'productos'

urlpatterns = [
    path('paletas/', views.ListadoPaletas.as_view(), name = 'listado_paletas' ),
    path('paletas/crear/', views.CrearPaleta.as_view(), name = 'crear_paleta' ),
    path('paletas/<int:pk>/', views.VerPaleta.as_view(), name = 'ver_paleta' ),
    path('paletas/<int:pk>/editar', views.EditarPaleta.as_view(), name = 'editar_paleta' ),
    path('paletas/<int:pk>/eliminar', views.EliminarPaleta.as_view(), name = 'eliminar_paleta' )
]

productos/models.py
from django.db import models

# Create your models here.
class Paleta(models.Model):
    marca = models.CharField(max_length=20)
    modelo = models.CharField(max_length=20)
    fecha = models.DateField()
    
    def __str__(self):
        return f'{self.id} - {self.modelo}'
    
    

productos/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from productos.models import Paleta
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class CrearPaleta(CreateView):
    model = Paleta
    template_name = "productos/crear_paleta.html"
    success_url = reverse_lazy('productos:listado_paletas')
    fields = ['modelo', 'marca', 'fecha']
    
class ListadoPaletas(ListView):
    model = Paleta
    template_name = "productos/listado_paletas.html"
    context_object_name = 'paletas'
    
class VerPaleta(LoginRequiredMixin, DetailView):
    model = Paleta
    template_name = "productos/ver_paleta.html"
    
class EditarPaleta(LoginRequiredMixin, UpdateView):
    model = Paleta
    template_name = "productos/editar_paleta.html"
    success_url = reverse_lazy('productos:listado_paletas')
    fields = ['modelo', 'marca', 'fecha']
    
class EliminarPaleta(DeleteView):
    model = Paleta
    template_name = "productos/eliminar_paleta.html"
    success_url = reverse_lazy('productos:listado_paletas')

    

productos/templates/productos/crear_paleta.html
{% extends "base.html" %}

{% block title_head %}
Crear Paleta
{% endblock title_head %}

{% block h1_header %}
Crear Paleta
{% endblock h1_header %}

{% block main %}
<form action={% url "productos:crear_paleta" %} method="POST">
    {% csrf_token %}

    
    {{form}}

    <input type="submit" value="Crear">

</form>
{% endblock main %}

productos/templates/productos/editar_paleta.html
{% extends "base.html" %}

{% block title_head %}
Editar Paleta
{% endblock title_head %}

{% block h1_header %}
Editar {{paleta}}
{% endblock h1_header %}

{% block main %}
<form action={% url "productos:editar_paleta" paleta.id %} method="POST">
    {% csrf_token %}

    {{form}}

    <input type="submit" value="Editar">
</form>

{% endblock main %}

productos/templates/productos/eliminar_paleta.html
{% extends "base.html" %}

{% block title_head %}
Eliminar Paleta
{% endblock title_head %}

{% block h1_header %}
Eliminar Paleta
{% endblock h1_header %}

{% block main %}
<form action={% url "productos:eliminar_paleta" paleta.id %} method="POST">
    {% csrf_token %}
    <p>Desea eliminar la paleta {{paleta}}?</p>

    <input type="submit" value="Confirmar">

</form>
{% endblock main %}

productos/templates/productos/listado_paletas.html
{% extends "base.html" %}

{% block title_head %}
Listado Paletas
{% endblock title_head %}

{% block h1_header %}
Listado de Paletas
{% endblock h1_header %}

{% block main %}
{% comment %} <form action={% url "inicio:buscar_auto" %}>
    {{form}}
    <input type="submit">
</form> {% endcomment %}
<a class="navbar-brand" href={% url "productos:crear_paleta" %}>Crear nueva paleta</a>

{% if paletas %}
<ul>
    {% for paleta in paletas %}
    <li>{{paleta}}
        | <a href={% url "productos:ver_paleta" paleta.id %}>Ver más</a>
        | <a href={% url "productos:editar_paleta" paleta.id %}>Editar</a>
        | <a href={% url "productos:eliminar_paleta" paleta.id %}>Eliminar</a> 
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No hay paletas registrados.</p>
{% endif %}

{% endblock main %}

productos/templates/productos/ver_paleta.html
{% extends "base.html" %}

{% block title_head %}
Ver Paleta
{% endblock title_head %}

{% block h1_header %}
{{paleta}}
{% endblock h1_header %}

{% block main %}
<ul>
    <li>Marca: {{paleta.marca}}</li>
    <li>Modelo: {{paleta.modelo}}</li>
    <li>Fecha: {{paleta.fecha}}</li>
</ul>

{% endblock main %}