django_60075/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('productos/', include('productos.urls')),
    path('usuarios/', include('usuarios.urls'))
    
]

inicio/urls.py
from django.urls import path
from inicio.views import (
    mi_vista, 
    inicio, 
    vista_datos1, 
    primer_template, 
    segundo_template, 
    crear_auto_correcto,
    buscar_auto, crear_auto,
    ver_auto, eliminar_auto, 
    editar_auto
)
app_name = "inicio"

urlpatterns = [
    path("mi-vista/", mi_vista, name="mi_vista"),
    path('', inicio, name="inicio"),
    path('vista-datos1/<nombre>/', vista_datos1, name="vista_datos1"),
    path('primer-template/', primer_template, name="primer_template"),
    path('segundo-template/', segundo_template, name="segundo_template"),
    path('crear-auto-correcto/<str:marca>/<str:modelo>/<int:anio>/', crear_auto_correcto, name="crear_auto_correcto"),
    path('buscar-auto/', buscar_auto, name="buscar_auto"),
    path('crear-auto/', crear_auto, name="crear_auto"),
    path('ver-auto/<int:id>', ver_auto, name="ver_auto"),
    path('eliminar-auto/<int:id>', eliminar_auto, name="eliminar_auto"),
    path('editar-auto/<int:id>', editar_auto, name="editar_auto")
]

productos/urls.py
from django.urls import path 
from productos import views

app_name = 'productos'

urlpatterns = [
    path('paletas/', views.ListadoPaletas.as_view(), name = 'listado_paletas' ),
    path('paletas/crear/', views.CrearPaleta.as_view(), name = 'crear_paleta' ),
    path('paletas/<int:pk>/', views.VerPaleta.as_view(), name = 'ver_paleta' ),
    path('paletas/<int:pk>/editar', views.EditarPaleta.as_view(), name = 'editar_paleta' ),
    path('paletas/<int:pk>/eliminar', views.EliminarPaleta.as_view(), name = 'eliminar_paleta' )
]

usuarios/urls.py
from django.urls import path
from usuarios import views
from django.contrib.auth.views import LogoutView

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title_head %}
            Template Base
            {% endblock title_head %}             
        </title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
         {% block link_stylesheet_heard %}
         <link href= {%static "css/styles.css"%} rel="stylesheet" />
         {% endblock link_stylesheet_heard %}
        
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href={% url "inicio:inicio" %}>Inicio</a>
                {% comment %} <a class="navbar-brand" href={% url "inicio:primer_template" %}>Primer Template</a>
                <a class="navbar-brand" href={% url "inicio:segundo_template" %}>Segundo Template</a> {% endcomment %}
                <a class="navbar-brand" href={% url "inicio:buscar_auto" %}>Buscar Auto</a>
                <a class="navbar-brand" href={% url "inicio:crear_auto" %}>Crear Auto</a>
                <a class="navbar-brand" href={% url "productos:crear_paleta" %}>Crear Paleta</a>
                <a class="navbar-brand" href={% url "productos:listado_paletas" %}>Paletas</a>
                {% if request.user.is_authenticated %}
                <a class="navbar-brand" href="#">{{request.user.username}}</a>
                <form action={% url "usuarios:logout" %} method= "POST">
                    {% csrf_token %}
                    <input type="submit" class= "btn btn-secondary" value = "Cerrar Sesion">
                </form>
                {% else %}
                <a class="btn btn-primary" href={% url "usuarios:login" %}>Iniciar Sesion</a>
                <a class="btn btn-info" href={% url "usuarios:register" %}>Registrarse</a>
                {% endif %}

                
                {% comment %} <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button> {% endcomment %}
                {% comment %} <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="#!">Sign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Log In</a></li>
                    </ul>
                </div> {% endcomment %}
            </div>
        </nav>
        <!-- Header-->
        {% block header %}
        <header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-5">
                    <h1 class="masthead-heading mb-0">
                        {% block h1_header %}Soy el base{% endblock h1_header %}
                    </h1>
                    <h2 class="masthead-subheading mb-0">Clase python</h2>
                    <a class="btn btn-primary btn-xl rounded-pill mt-5" href="#scroll">Leer más</a>
                </div>
            </div>
            <div class="bg-circle-1 bg-circle"></div>
            <div class="bg-circle-2 bg-circle"></div>
            <div class="bg-circle-3 bg-circle"></div>
            <div class="bg-circle-4 bg-circle"></div>
        </header>
        {% endblock header %}
        <!-- Content section 1-->
        {% comment %} <section id="scroll">
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6 order-lg-2">
                        <div class="p-5"><img class="img-fluid rounded-circle" src={%static "assets/img/01.jpg"%} alt="..." /></div>
                    </div>
                    <div class="col-lg-6 order-lg-1">
                        <div class="p-5">
                            <h2 class="display-4">For those about to rock...</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Content section 2-->
        <section>
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6">
                        <div class="p-5"><img class="img-fluid rounded-circle" src= {%static "assets/img/02.jpg"%} alt="..." /></div>
                    </div>
                    <div class="col-lg-6">
                        <div class="p-5">
                            <h2 class="display-4">We salute you!</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Content section 3-->
        <section>
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6 order-lg-2">
                        <div class="p-5"><img class="img-fluid rounded-circle" src={%static "assets/img/03.jpg"%} alt="..." /></div>
                    </div>
                    <div class="col-lg-6 order-lg-1">
                        <div class="p-5">
                            <h2 class="display-4">Let there be rock!</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section> {% endcomment %}
        <main>
            {% block main %}{% endblock main %}
        </main>
        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}%}></script>
    </body>
</html>

templates/primer_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        Daniel pudo con el codigo
    </h1>
</body>
</html>